// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crypto.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInput struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Privkey              string   `protobuf:"bytes,2,opt,name=privkey,proto3" json:"privkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInput) Reset()         { *m = SignInput{} }
func (m *SignInput) String() string { return proto.CompactTextString(m) }
func (*SignInput) ProtoMessage()    {}
func (*SignInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{0}
}

func (m *SignInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInput.Unmarshal(m, b)
}
func (m *SignInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInput.Marshal(b, m, deterministic)
}
func (m *SignInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInput.Merge(m, src)
}
func (m *SignInput) XXX_Size() int {
	return xxx_messageInfo_SignInput.Size(m)
}
func (m *SignInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInput.DiscardUnknown(m)
}

var xxx_messageInfo_SignInput proto.InternalMessageInfo

func (m *SignInput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SignInput) GetPrivkey() string {
	if m != nil {
		return m.Privkey
	}
	return ""
}

type VerifyInput struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Pubkey               string   `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyInput) Reset()         { *m = VerifyInput{} }
func (m *VerifyInput) String() string { return proto.CompactTextString(m) }
func (*VerifyInput) ProtoMessage()    {}
func (*VerifyInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{1}
}

func (m *VerifyInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyInput.Unmarshal(m, b)
}
func (m *VerifyInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyInput.Marshal(b, m, deterministic)
}
func (m *VerifyInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyInput.Merge(m, src)
}
func (m *VerifyInput) XXX_Size() int {
	return xxx_messageInfo_VerifyInput.Size(m)
}
func (m *VerifyInput) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyInput.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyInput proto.InternalMessageInfo

func (m *VerifyInput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *VerifyInput) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *VerifyInput) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

type SignResult struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignResult) Reset()         { *m = SignResult{} }
func (m *SignResult) String() string { return proto.CompactTextString(m) }
func (*SignResult) ProtoMessage()    {}
func (*SignResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_527278fb02d03321, []int{2}
}

func (m *SignResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignResult.Unmarshal(m, b)
}
func (m *SignResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignResult.Marshal(b, m, deterministic)
}
func (m *SignResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResult.Merge(m, src)
}
func (m *SignResult) XXX_Size() int {
	return xxx_messageInfo_SignResult.Size(m)
}
func (m *SignResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResult.DiscardUnknown(m)
}

var xxx_messageInfo_SignResult proto.InternalMessageInfo

func (m *SignResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *SignResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*SignInput)(nil), "api.SignInput")
	proto.RegisterType((*VerifyInput)(nil), "api.VerifyInput")
	proto.RegisterType((*SignResult)(nil), "api.SignResult")
}

func init() { proto.RegisterFile("crypto.proto", fileDescriptor_527278fb02d03321) }

var fileDescriptor_527278fb02d03321 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2e, 0xaa, 0x2c,
	0x28, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xb2, 0xe7,
	0xe2, 0x0c, 0xce, 0x4c, 0xcf, 0xf3, 0xcc, 0x2b, 0x28, 0x2d, 0x11, 0x92, 0xe0, 0x62, 0xcf, 0x4d,
	0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x41, 0x32,
	0x05, 0x45, 0x99, 0x65, 0xd9, 0xa9, 0x95, 0x12, 0x4c, 0x10, 0x19, 0x28, 0x57, 0x29, 0x96, 0x8b,
	0x3b, 0x2c, 0xb5, 0x28, 0x33, 0xad, 0x92, 0x90, 0x11, 0x32, 0x5c, 0x9c, 0xc5, 0x99, 0xe9, 0x79,
	0x89, 0x25, 0xa5, 0x45, 0xa9, 0x50, 0x43, 0x10, 0x02, 0x42, 0x62, 0x5c, 0x6c, 0x05, 0xa5, 0x49,
	0x20, 0xf3, 0x99, 0xc1, 0x52, 0x50, 0x9e, 0x92, 0x09, 0x17, 0x17, 0xc8, 0x7d, 0x41, 0xa9, 0xc5,
	0xa5, 0x39, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0xf9, 0xd9, 0x60, 0x83, 0x39, 0x82, 0x98, 0xf2, 0xb3,
	0x41, 0xba, 0x8a, 0xc0, 0x32, 0x50, 0x03, 0xa1, 0x3c, 0xa3, 0x24, 0x2e, 0x36, 0x67, 0xb0, 0x57,
	0x85, 0x34, 0xb9, 0x58, 0x40, 0xfa, 0x85, 0xf8, 0xf4, 0x12, 0x0b, 0x32, 0xf5, 0xe0, 0x5e, 0x95,
	0xe2, 0x87, 0xf3, 0x21, 0x46, 0x2b, 0x31, 0x08, 0xe9, 0x72, 0xb1, 0x41, 0x7c, 0x22, 0x24, 0x00,
	0x96, 0x44, 0xf2, 0x16, 0x16, 0xe5, 0x49, 0x6c, 0xe0, 0x50, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x2f, 0x7c, 0xc4, 0x27, 0x55, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CryptoClient is the client API for Crypto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CryptoClient interface {
	Sign(ctx context.Context, in *SignInput, opts ...grpc.CallOption) (*SignResult, error)
	Verify(ctx context.Context, in *VerifyInput, opts ...grpc.CallOption) (*SignResult, error)
}

type cryptoClient struct {
	cc *grpc.ClientConn
}

func NewCryptoClient(cc *grpc.ClientConn) CryptoClient {
	return &cryptoClient{cc}
}

func (c *cryptoClient) Sign(ctx context.Context, in *SignInput, opts ...grpc.CallOption) (*SignResult, error) {
	out := new(SignResult)
	err := c.cc.Invoke(ctx, "/api.Crypto/Sign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoClient) Verify(ctx context.Context, in *VerifyInput, opts ...grpc.CallOption) (*SignResult, error) {
	out := new(SignResult)
	err := c.cc.Invoke(ctx, "/api.Crypto/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoServer is the server API for Crypto service.
type CryptoServer interface {
	Sign(context.Context, *SignInput) (*SignResult, error)
	Verify(context.Context, *VerifyInput) (*SignResult, error)
}

// UnimplementedCryptoServer can be embedded to have forward compatible implementations.
type UnimplementedCryptoServer struct {
}

func (*UnimplementedCryptoServer) Sign(ctx context.Context, req *SignInput) (*SignResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (*UnimplementedCryptoServer) Verify(ctx context.Context, req *VerifyInput) (*SignResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}

func RegisterCryptoServer(s *grpc.Server, srv CryptoServer) {
	s.RegisterService(&_Crypto_serviceDesc, srv)
}

func _Crypto_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Crypto/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServer).Sign(ctx, req.(*SignInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Crypto_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Crypto/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServer).Verify(ctx, req.(*VerifyInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Crypto_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Crypto",
	HandlerType: (*CryptoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sign",
			Handler:    _Crypto_Sign_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Crypto_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crypto.proto",
}
