// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smartcontract.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SmartContractInput struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	EntryFunc            string   `protobuf:"bytes,2,opt,name=entry_func,json=entryFunc,proto3" json:"entry_func,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartContractInput) Reset()         { *m = SmartContractInput{} }
func (m *SmartContractInput) String() string { return proto.CompactTextString(m) }
func (*SmartContractInput) ProtoMessage()    {}
func (*SmartContractInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_smartcontract_1bc0051f1de6b7aa, []int{0}
}
func (m *SmartContractInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartContractInput.Unmarshal(m, b)
}
func (m *SmartContractInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartContractInput.Marshal(b, m, deterministic)
}
func (dst *SmartContractInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartContractInput.Merge(dst, src)
}
func (m *SmartContractInput) XXX_Size() int {
	return xxx_messageInfo_SmartContractInput.Size(m)
}
func (m *SmartContractInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartContractInput.DiscardUnknown(m)
}

var xxx_messageInfo_SmartContractInput proto.InternalMessageInfo

func (m *SmartContractInput) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *SmartContractInput) GetEntryFunc() string {
	if m != nil {
		return m.EntryFunc
	}
	return ""
}

type SmartContractResult struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartContractResult) Reset()         { *m = SmartContractResult{} }
func (m *SmartContractResult) String() string { return proto.CompactTextString(m) }
func (*SmartContractResult) ProtoMessage()    {}
func (*SmartContractResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_smartcontract_1bc0051f1de6b7aa, []int{1}
}
func (m *SmartContractResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartContractResult.Unmarshal(m, b)
}
func (m *SmartContractResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartContractResult.Marshal(b, m, deterministic)
}
func (dst *SmartContractResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartContractResult.Merge(dst, src)
}
func (m *SmartContractResult) XXX_Size() int {
	return xxx_messageInfo_SmartContractResult.Size(m)
}
func (m *SmartContractResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartContractResult.DiscardUnknown(m)
}

var xxx_messageInfo_SmartContractResult proto.InternalMessageInfo

func (m *SmartContractResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *SmartContractResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*SmartContractInput)(nil), "api.SmartContractInput")
	proto.RegisterType((*SmartContractResult)(nil), "api.SmartContractResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SmartContractClient is the client API for SmartContract service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SmartContractClient interface {
	Call(ctx context.Context, in *SmartContractInput, opts ...grpc.CallOption) (*SmartContractResult, error)
}

type smartContractClient struct {
	cc *grpc.ClientConn
}

func NewSmartContractClient(cc *grpc.ClientConn) SmartContractClient {
	return &smartContractClient{cc}
}

func (c *smartContractClient) Call(ctx context.Context, in *SmartContractInput, opts ...grpc.CallOption) (*SmartContractResult, error) {
	out := new(SmartContractResult)
	err := c.cc.Invoke(ctx, "/api.SmartContract/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartContractServer is the server API for SmartContract service.
type SmartContractServer interface {
	Call(context.Context, *SmartContractInput) (*SmartContractResult, error)
}

func RegisterSmartContractServer(s *grpc.Server, srv SmartContractServer) {
	s.RegisterService(&_SmartContract_serviceDesc, srv)
}

func _SmartContract_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmartContractInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SmartContract/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractServer).Call(ctx, req.(*SmartContractInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _SmartContract_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SmartContract",
	HandlerType: (*SmartContractServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _SmartContract_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smartcontract.proto",
}

func init() { proto.RegisterFile("smartcontract.proto", fileDescriptor_smartcontract_1bc0051f1de6b7aa) }

var fileDescriptor_smartcontract_1bc0051f1de6b7aa = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xce, 0x4d, 0x2c,
	0x2a, 0x49, 0xce, 0xcf, 0x2b, 0x29, 0x4a, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x72, 0xe5, 0x12, 0x0a, 0x06, 0xc9, 0x39, 0x43, 0xe5, 0x3c, 0xf3,
	0x0a, 0x4a, 0x4b, 0x84, 0x04, 0xb8, 0x98, 0x4b, 0x8b, 0x32, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x40, 0x4c, 0x21, 0x59, 0x2e, 0xae, 0x54, 0xa0, 0x8a, 0xca, 0xf8, 0xb4, 0xd2, 0xbc, 0x64,
	0x09, 0x26, 0xb0, 0x04, 0x27, 0x58, 0xc4, 0x0d, 0x28, 0xa0, 0x64, 0xcb, 0x25, 0x8c, 0x62, 0x4c,
	0x50, 0x6a, 0x71, 0x69, 0x4e, 0x89, 0x10, 0x1f, 0x17, 0x53, 0x7e, 0x36, 0xd8, 0x18, 0x8e, 0x20,
	0x20, 0x4b, 0x48, 0x8c, 0x8b, 0xad, 0x08, 0x2c, 0x03, 0x35, 0x01, 0xca, 0x33, 0xf2, 0xe1, 0xe2,
	0x45, 0xd1, 0x2e, 0x64, 0xcd, 0xc5, 0xe2, 0x9c, 0x98, 0x93, 0x23, 0x24, 0xae, 0x07, 0x74, 0xa4,
	0x1e, 0xa6, 0x0b, 0xa5, 0x24, 0x30, 0x25, 0x20, 0x76, 0x2a, 0x31, 0x24, 0xb1, 0x81, 0xfd, 0x67,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x99, 0x8b, 0x70, 0x59, 0xf6, 0x00, 0x00, 0x00,
}
