// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTransactionRequestMessage struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionRequestMessage) Reset()         { *m = GetTransactionRequestMessage{} }
func (m *GetTransactionRequestMessage) String() string { return proto.CompactTextString(m) }
func (*GetTransactionRequestMessage) ProtoMessage()    {}
func (*GetTransactionRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *GetTransactionRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionRequestMessage.Unmarshal(m, b)
}
func (m *GetTransactionRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionRequestMessage.Marshal(b, m, deterministic)
}
func (m *GetTransactionRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionRequestMessage.Merge(m, src)
}
func (m *GetTransactionRequestMessage) XXX_Size() int {
	return xxx_messageInfo_GetTransactionRequestMessage.Size(m)
}
func (m *GetTransactionRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionRequestMessage proto.InternalMessageInfo

func (m *GetTransactionRequestMessage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetTransactionResponseMessage struct {
	Transaction          string   `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionResponseMessage) Reset()         { *m = GetTransactionResponseMessage{} }
func (m *GetTransactionResponseMessage) String() string { return proto.CompactTextString(m) }
func (*GetTransactionResponseMessage) ProtoMessage()    {}
func (*GetTransactionResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *GetTransactionResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionResponseMessage.Unmarshal(m, b)
}
func (m *GetTransactionResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionResponseMessage.Marshal(b, m, deterministic)
}
func (m *GetTransactionResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionResponseMessage.Merge(m, src)
}
func (m *GetTransactionResponseMessage) XXX_Size() int {
	return xxx_messageInfo_GetTransactionResponseMessage.Size(m)
}
func (m *GetTransactionResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionResponseMessage proto.InternalMessageInfo

func (m *GetTransactionResponseMessage) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTransactionRequestMessage)(nil), "api.GetTransactionRequestMessage")
	proto.RegisterType((*GetTransactionResponseMessage)(nil), "api.GetTransactionResponseMessage")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x29, 0x4a, 0xcc,
	0x2b, 0x4e, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e,
	0x2c, 0xc8, 0x54, 0xb2, 0xe0, 0x92, 0x71, 0x4f, 0x2d, 0x09, 0x41, 0x48, 0x06, 0xa5, 0x16, 0x96,
	0xa6, 0x16, 0x97, 0xf8, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0x49, 0x70, 0xb1, 0x27, 0xa6,
	0xa4, 0x14, 0xa5, 0x16, 0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x4a, 0x8e,
	0x5c, 0xb2, 0xe8, 0x3a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x61, 0x5a, 0x15, 0xb8, 0xb8, 0x91,
	0x2c, 0x85, 0x6a, 0x47, 0x16, 0x32, 0xca, 0xe4, 0xe2, 0x46, 0xd2, 0x2f, 0x14, 0xc5, 0xc5, 0x8f,
	0x6a, 0x62, 0xb1, 0x90, 0xa2, 0x5e, 0x62, 0x41, 0xa6, 0x1e, 0x3e, 0x17, 0x4a, 0x29, 0x61, 0x55,
	0x82, 0xe2, 0x14, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x9f, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x91, 0x3d, 0xff, 0x5d, 0x08, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionClient is the client API for Transaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionClient interface {
	GetTransactions(ctx context.Context, in *GetTransactionRequestMessage, opts ...grpc.CallOption) (*GetTransactionResponseMessage, error)
}

type transactionClient struct {
	cc *grpc.ClientConn
}

func NewTransactionClient(cc *grpc.ClientConn) TransactionClient {
	return &transactionClient{cc}
}

func (c *transactionClient) GetTransactions(ctx context.Context, in *GetTransactionRequestMessage, opts ...grpc.CallOption) (*GetTransactionResponseMessage, error) {
	out := new(GetTransactionResponseMessage)
	err := c.cc.Invoke(ctx, "/api.Transaction/GetTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServer is the server API for Transaction service.
type TransactionServer interface {
	GetTransactions(context.Context, *GetTransactionRequestMessage) (*GetTransactionResponseMessage, error)
}

// UnimplementedTransactionServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionServer struct {
}

func (*UnimplementedTransactionServer) GetTransactions(ctx context.Context, req *GetTransactionRequestMessage) (*GetTransactionResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactions not implemented")
}

func RegisterTransactionServer(s *grpc.Server, srv TransactionServer) {
	s.RegisterService(&_Transaction_serviceDesc, srv)
}

func _Transaction_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Transaction/GetTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetTransactions(ctx, req.(*GetTransactionRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transaction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Transaction",
	HandlerType: (*TransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransactions",
			Handler:    _Transaction_GetTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
